DROP TABLE IF EXISTS APP_USERS;

CREATE TABLE APP_USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  user_role VARCHAR(250) NOT NULL
);